kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: kind-cluster
runtimeConfig:
  "api/alpha": "false"
nodes:
- role: control-planeddd
- role: worker
- role: worker
- role: worker
containerdConfigPatches:
- |-  
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5000"]
    endpoint = ["http://kind-registry:5000"]
