apiVersion: apps/v1
kind: Deployment
metadata:
  name: myserver2-deployment
  labels:
    app: myserver2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myserver2
  template:
    metadata:
      labels:
        app: myserver2
    spec:
      containers:
      - name: myserver2
        image:  nginx:latest
        ports:
        - containerPort: 80
